# -*- coding: utf-8 -*-
"""variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iVIQCwCNYst3iGmSq28egMf4N1FM6dFU
"""

# Variable declaration
Name = "Denis"
age = 22
city = "Nairobi"

# Control structure
if age > 18:
    print(Name, "is an adult.")

# Nested control structure
if city == "Nairobi":
        print(Name, "lives in", city)

if age > 18:
    if age >= 18:
        print("Age check passed!")